/*
Signadot Routes API

The Routes API provides access to in-cluster routing configuration set up by  the Signadot Operator. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the TrafficManager type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrafficManager{}

// TrafficManager Traffic Manager based routing specification for this workload port
type TrafficManager struct {
	// List of possible addresses to choose for the the `signadot-next-host` header
	NextDestinations []Location `json:"nextDestinations,omitempty"`
	// Whether any traffic must be sent to the traffic manager.  If false, the determination is made by the `sd-traffic` header
	AllTraffic *bool `json:"allTraffic,omitempty"`
}

// NewTrafficManager instantiates a new TrafficManager object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrafficManager() *TrafficManager {
	this := TrafficManager{}
	return &this
}

// NewTrafficManagerWithDefaults instantiates a new TrafficManager object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrafficManagerWithDefaults() *TrafficManager {
	this := TrafficManager{}
	return &this
}

// GetNextDestinations returns the NextDestinations field value if set, zero value otherwise.
func (o *TrafficManager) GetNextDestinations() []Location {
	if o == nil || IsNil(o.NextDestinations) {
		var ret []Location
		return ret
	}
	return o.NextDestinations
}

// GetNextDestinationsOk returns a tuple with the NextDestinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficManager) GetNextDestinationsOk() ([]Location, bool) {
	if o == nil || IsNil(o.NextDestinations) {
		return nil, false
	}
	return o.NextDestinations, true
}

// HasNextDestinations returns a boolean if a field has been set.
func (o *TrafficManager) HasNextDestinations() bool {
	if o != nil && !IsNil(o.NextDestinations) {
		return true
	}

	return false
}

// SetNextDestinations gets a reference to the given []Location and assigns it to the NextDestinations field.
func (o *TrafficManager) SetNextDestinations(v []Location) {
	o.NextDestinations = v
}

// GetAllTraffic returns the AllTraffic field value if set, zero value otherwise.
func (o *TrafficManager) GetAllTraffic() bool {
	if o == nil || IsNil(o.AllTraffic) {
		var ret bool
		return ret
	}
	return *o.AllTraffic
}

// GetAllTrafficOk returns a tuple with the AllTraffic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrafficManager) GetAllTrafficOk() (*bool, bool) {
	if o == nil || IsNil(o.AllTraffic) {
		return nil, false
	}
	return o.AllTraffic, true
}

// HasAllTraffic returns a boolean if a field has been set.
func (o *TrafficManager) HasAllTraffic() bool {
	if o != nil && !IsNil(o.AllTraffic) {
		return true
	}

	return false
}

// SetAllTraffic gets a reference to the given bool and assigns it to the AllTraffic field.
func (o *TrafficManager) SetAllTraffic(v bool) {
	o.AllTraffic = &v
}

func (o TrafficManager) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrafficManager) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextDestinations) {
		toSerialize["nextDestinations"] = o.NextDestinations
	}
	if !IsNil(o.AllTraffic) {
		toSerialize["allTraffic"] = o.AllTraffic
	}
	return toSerialize, nil
}

type NullableTrafficManager struct {
	value *TrafficManager
	isSet bool
}

func (v NullableTrafficManager) Get() *TrafficManager {
	return v.value
}

func (v *NullableTrafficManager) Set(val *TrafficManager) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficManager) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficManager) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficManager(val *TrafficManager) *NullableTrafficManager {
	return &NullableTrafficManager{value: val, isSet: true}
}

func (v NullableTrafficManager) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficManager) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


