/*
Signadot Routes API

The Signadot Routes API provides access to routing rules pertinent to Signadot Sandboxes on a cluster with the Signadot Operator (>= v0.14.2) installed. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the SandboxedWorkload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxedWorkload{}

// SandboxedWorkload A SandboxedWorkload represents a Fork or a Local workload running in a sandbox.
type SandboxedWorkload struct {
	// The routing key of a Sandbox
	SandboxID *string `json:"sandboxID,omitempty"`
	Baseline *BaselineWorkload `json:"baseline,omitempty"`
}

// NewSandboxedWorkload instantiates a new SandboxedWorkload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxedWorkload() *SandboxedWorkload {
	this := SandboxedWorkload{}
	return &this
}

// NewSandboxedWorkloadWithDefaults instantiates a new SandboxedWorkload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxedWorkloadWithDefaults() *SandboxedWorkload {
	this := SandboxedWorkload{}
	return &this
}

// GetSandboxID returns the SandboxID field value if set, zero value otherwise.
func (o *SandboxedWorkload) GetSandboxID() string {
	if o == nil || IsNil(o.SandboxID) {
		var ret string
		return ret
	}
	return *o.SandboxID
}

// GetSandboxIDOk returns a tuple with the SandboxID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxedWorkload) GetSandboxIDOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxID) {
		return nil, false
	}
	return o.SandboxID, true
}

// HasSandboxID returns a boolean if a field has been set.
func (o *SandboxedWorkload) HasSandboxID() bool {
	if o != nil && !IsNil(o.SandboxID) {
		return true
	}

	return false
}

// SetSandboxID gets a reference to the given string and assigns it to the SandboxID field.
func (o *SandboxedWorkload) SetSandboxID(v string) {
	o.SandboxID = &v
}

// GetBaseline returns the Baseline field value if set, zero value otherwise.
func (o *SandboxedWorkload) GetBaseline() BaselineWorkload {
	if o == nil || IsNil(o.Baseline) {
		var ret BaselineWorkload
		return ret
	}
	return *o.Baseline
}

// GetBaselineOk returns a tuple with the Baseline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxedWorkload) GetBaselineOk() (*BaselineWorkload, bool) {
	if o == nil || IsNil(o.Baseline) {
		return nil, false
	}
	return o.Baseline, true
}

// HasBaseline returns a boolean if a field has been set.
func (o *SandboxedWorkload) HasBaseline() bool {
	if o != nil && !IsNil(o.Baseline) {
		return true
	}

	return false
}

// SetBaseline gets a reference to the given BaselineWorkload and assigns it to the Baseline field.
func (o *SandboxedWorkload) SetBaseline(v BaselineWorkload) {
	o.Baseline = &v
}

func (o SandboxedWorkload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxedWorkload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SandboxID) {
		toSerialize["sandboxID"] = o.SandboxID
	}
	if !IsNil(o.Baseline) {
		toSerialize["baseline"] = o.Baseline
	}
	return toSerialize, nil
}

type NullableSandboxedWorkload struct {
	value *SandboxedWorkload
	isSet bool
}

func (v NullableSandboxedWorkload) Get() *SandboxedWorkload {
	return v.value
}

func (v *NullableSandboxedWorkload) Set(val *SandboxedWorkload) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxedWorkload) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxedWorkload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxedWorkload(val *SandboxedWorkload) *NullableSandboxedWorkload {
	return &NullableSandboxedWorkload{value: val, isSet: true}
}

func (v NullableSandboxedWorkload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxedWorkload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


